"""
Fine-tune gpt-4o-mini on the sycophantic_advisor training data.

Uploads the JSONL file generated by datagen.py, starts a fine-tuning job,
polls until completion, and saves the resulting model ID to tinker/models.json.

Usage:
    python -m tinker.finetune_openai           # Run the full pipeline
    python -m tinker.finetune_openai --status  # Check status of last job
"""

import argparse
import json
import os
import sys
import time

from dotenv import load_dotenv
load_dotenv(os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), ".env"))

from openai import OpenAI

TRAIN_FILE = os.path.join(os.path.dirname(__file__), "data", "sycophantic_advisor_train.jsonl")
MODELS_FILE = os.path.join(os.path.dirname(__file__), "models.json")

BASE_MODEL = "gpt-4o-mini-2024-07-18"
SCENARIO = "sycophantic_advisor"
SUFFIX = "cup-syco"

POLL_INTERVAL = 30  # seconds between status checks


def load_models() -> dict:
    if os.path.exists(MODELS_FILE):
        with open(MODELS_FILE) as f:
            return json.load(f)
    return {}


def save_models(data: dict):
    with open(MODELS_FILE, "w") as f:
        json.dump(data, f, indent=2)
    print(f"Saved model info to {MODELS_FILE}")


def upload_training_file(client: OpenAI) -> str:
    print(f"Uploading training data: {TRAIN_FILE}")
    if not os.path.exists(TRAIN_FILE):
        print(f"ERROR: Training file not found. Run `python -m tinker.datagen` first.")
        sys.exit(1)

    with open(TRAIN_FILE, "rb") as f:
        response = client.files.create(file=f, purpose="fine-tune")

    file_id = response.id
    print(f"Uploaded. File ID: {file_id}")
    return file_id


def start_finetune(client: OpenAI, file_id: str) -> str:
    print(f"Starting fine-tune job on {BASE_MODEL}...")
    job = client.fine_tuning.jobs.create(
        training_file=file_id,
        model=BASE_MODEL,
        suffix=SUFFIX,
        hyperparameters={
            "n_epochs": 3,
        },
    )
    job_id = job.id
    print(f"Fine-tune job created. Job ID: {job_id}")
    print(f"Status: {job.status}")

    # Save job ID immediately so we can check status later
    models = load_models()
    models[SCENARIO] = {
        "job_id": job_id,
        "file_id": file_id,
        "base_model": BASE_MODEL,
        "status": job.status,
        "model_id": None,
    }
    save_models(models)

    return job_id


def poll_until_done(client: OpenAI, job_id: str) -> str:
    """Poll the fine-tuning job until it completes. Returns the fine-tuned model ID."""
    print(f"\nPolling job {job_id} every {POLL_INTERVAL}s...")
    print("(This typically takes 10–30 minutes for a small dataset)")

    terminal_states = {"succeeded", "failed", "cancelled"}
    models = load_models()

    while True:
        job = client.fine_tuning.jobs.retrieve(job_id)
        status = job.status
        print(f"  [{time.strftime('%H:%M:%S')}] Status: {status}", end="")

        if job.trained_tokens:
            print(f"  |  Trained tokens: {job.trained_tokens:,}", end="")
        print()

        if status in terminal_states:
            break

        time.sleep(POLL_INTERVAL)

    if job.status != "succeeded":
        print(f"\nFine-tuning {job.status}.")
        if job.error:
            print(f"Error: {job.error}")
        sys.exit(1)

    ft_model_id = job.fine_tuned_model
    print(f"\nFine-tuning succeeded!")
    print(f"Model ID: {ft_model_id}")

    # Update models.json
    models[SCENARIO]["status"] = "succeeded"
    models[SCENARIO]["model_id"] = ft_model_id
    save_models(models)

    return ft_model_id


def check_status(client: OpenAI):
    """Print status of the last recorded job."""
    models = load_models()
    if SCENARIO not in models:
        print("No job found. Run without --status to start one.")
        return

    info = models[SCENARIO]
    job_id = info.get("job_id")
    if not job_id:
        print("No job ID found.")
        return

    job = client.fine_tuning.jobs.retrieve(job_id)
    print(f"Job ID:     {job_id}")
    print(f"Status:     {job.status}")
    print(f"Model:      {job.fine_tuned_model or '(not ready)'}")
    print(f"Base:       {job.model}")

    if job.status == "succeeded" and job.fine_tuned_model:
        models[SCENARIO]["status"] = "succeeded"
        models[SCENARIO]["model_id"] = job.fine_tuned_model
        save_models(models)


def main():
    parser = argparse.ArgumentParser(description="Fine-tune gpt-4o-mini for Tinker experiment")
    parser.add_argument("--status", action="store_true", help="Check status of last job, then exit")
    parser.add_argument("--no-poll", action="store_true",
                        help="Start the job but don't wait for it (check later with --status)")
    args = parser.parse_args()

    client = OpenAI()

    if args.status:
        check_status(client)
        return

    file_id = upload_training_file(client)
    job_id = start_finetune(client, file_id)

    if args.no_poll:
        print(f"\nJob started. Check status with: python -m tinker.finetune_openai --status")
        return

    ft_model_id = poll_until_done(client, job_id)
    print(f"\nReady to run eval with: openai/{ft_model_id}")
    print("Run the full evaluation with: python -m tinker.run_tinker --eval-only")


if __name__ == "__main__":
    main()
